#include "matlab_funcs.hpp"

Matrix18_18 AUG_JacobianX(Vector18 in1, Vector4 in2) {
  // AUG_JacobianX
  //     OUT1 = AUG_JacobianX(IN1,IN2)

  //    This function was generated by the Symbolic Math Toolbox version 24.2.
  //    11-Aug-2025 16:49:06

  float b4 = in1[15];
  float b5 = in1[16];
  float b6 = in1[17];
  float omega1 = in1[9];
  float omega2 = in1[10];
  float omega3 = in1[11];
  float phi = in2[1];
  float q1 = in1[6];
  float q2 = in1[7];
  float q3 = in1[8];
  float theta = in2[0];
  float thrust = in2[2];
  float t2 = cos(phi);
  float t3 = cos(theta);
  float t4 = sin(phi);
  float t5 = sin(theta);
  float t6 = q1 * 2.0;
  float t7 = q2 * 2.0;
  float t8 = q3 * 2.0;
  float t9 = pow(q1, 2);
  float t10 = pow(q2, 2);
  float t11 = pow(q3, 2);
  float t12 = -omega1;
  float t13 = -omega2;
  float t14 = -omega3;
  float t15 = -q2;
  float t16 = b4 / 2.0;
  float t17 = b6 / 2.0;
  float t18 = b5 * (3.0 / 2.0);
  float t19 = omega1 / 2.0;
  float t20 = omega3 / 2.0;
  float t21 = omega2 * (3.0 / 2.0);
  float t22 = q1 / 2.0;
  float t23 = q2 / 2.0;
  float t24 = q1 * (3.0 / 2.0);
  float t25 = q3 / 2.0;
  float t26 = q3 * (3.0 / 2.0);
  float t33 = b4 * (3.0 / 5.3e+1);
  float t34 = b5 * (3.0 / 5.3e+1);
  float t35 = b6 * (3.0 / 5.3e+1);
  float t36 = omega1 * (3.0 / 5.3e+1);
  float t37 = omega2 * (3.0 / 5.3e+1);
  float t38 = omega3 * (3.0 / 5.3e+1);
  float t27 = -t9;
  float t28 = -t10;
  float t29 = -t11;
  float t30 = b4 + t12;
  float t31 = b5 + t13;
  float t32 = b6 + t14;
  float t39 = -t23;
  float t40 = -t33;
  float t41 = -t36;
  float t42 = t36 + t40;
  float t43 = t33 + t41;
  float t44 = t27 + t28 + t29 + 1.0;
  float t45 = sqrt(t44);
  float t46 = 1.0 / t45;
  float t47 = t45 * 2.0;
  float t48 = t45 / 2.0;
  float t49 = q2 * t6 * t46;
  float t50 = q3 * t6 * t46;
  float t51 = q3 * t7 * t46;
  float t52 = -t48;
  float t56 = q1 * q2 * t46 * -2.0;
  float t57 = q1 * q3 * t46 * -2.0;
  float t58 = q2 * q3 * t46 * -2.0;
  float t59 = t9 * t46 * -2.0;
  float t60 = t10 * t46 * -2.0;
  float t61 = t11 * t46 * -2.0;
  float t62 = t6 + t51;
  float t63 = t7 + t50;
  float t64 = t8 + t49;
  float t65 = t6 + t58;
  float t66 = t7 + t57;
  float t67 = t8 + t56;
  float t68 = t47 + t59;
  float t69 = t47 + t60;
  float t70 = t47 + t61;
  Matrix18_18 rval;
  rval << 0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      1.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      1.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      1.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      t5 * t67 * thrust * (-2.0e+2 / 1.99e+2) + t3 * t4 * t63 * thrust * (2.0e+2 / 1.99e+2),
      t5 * t68 * thrust * (2.0e+2 / 1.99e+2) - q1 * t3 * t4 * thrust * (8.0e+2 / 1.99e+2) + t2 * t3 * t66 * thrust * (2.0e+2 / 1.99e+2),
      q1 * t5 * thrust * (8.0e+2 / 1.99e+2) + t2 * t3 * t64 * thrust * (2.0e+2 / 1.99e+2) + t3 * t4 * t68 * thrust * (2.0e+2 / 1.99e+2),
      q1 * t32 * t46 * (-1.0 / 2.0),
      -b6 + omega3 + t16 - t19 + t22 * t31 * t46,
      t18 - t21 - (q1 * t30 * t46) / 2.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      t5 * t69 * thrust * (-2.0e+2 / 1.99e+2) - q2 * t2 * t3 * thrust * (8.0e+2 / 1.99e+2) + t3 * t4 * t62 * thrust * (2.0e+2 / 1.99e+2),
      t5 * t64 * thrust * (-2.0e+2 / 1.99e+2) + t2 * t3 * t65 * thrust * (2.0e+2 / 1.99e+2),
      q2 * t5 * thrust * (8.0e+2 / 1.99e+2) - t2 * t3 * t69 * thrust * (2.0e+2 / 1.99e+2) + t3 * t4 * t67 * thrust * (2.0e+2 / 1.99e+2),
      -t16 + t19 + t32 - (q2 * t32 * t46) / 2.0,
      t23 * t31 * t46,
      -b4 + omega1 + t17 - t20 - (q2 * t30 * t46) / 2.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      t5 * t65 * thrust * (-2.0e+2 / 1.99e+2) - q3 * t2 * t3 * thrust * (8.0e+2 / 1.99e+2) - t3 * t4 * t70 * thrust * (2.0e+2 / 1.99e+2),
      t5 * t63 * thrust * (-2.0e+2 / 1.99e+2) - q3 * t3 * t4 * thrust * (8.0e+2 / 1.99e+2) + t2 * t3 * t70 * thrust * (2.0e+2 / 1.99e+2),
      t2 * t3 * t62 * thrust * (2.0e+2 / 1.99e+2) + t3 * t4 * t66 * thrust * (2.0e+2 / 1.99e+2),
      -t18 + t21 - (q3 * t32 * t46) / 2.0,
      -t17 + t20 + t30 + t25 * t31 * t46,
      q3 * t30 * t46 * (-1.0 / 2.0),
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      t23,
      -q3 - t22,
      q2 + t52,
      0.0,
      -t35 + t38,
      t34 - t37,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      t26,
      t48,
      -t24,
      0.0,
      0.0,
      t43,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      t15 + t52,
      q1 + t25,
      t39,
      0.0,
      t42,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      -1.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      -1.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      -1.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      t39,
      q3 + t22,
      t15 + t48,
      0.0,
      t35 - t38,
      -t34 + t37,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      -t26,
      t52,
      t24,
      0.0,
      0.0,
      t42,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      q2 + t48,
      -q1 - t25,
      t23,
      0.0,
      t43,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0;
  return rval;
}

Vector18 AUG_plantfcn(Vector18 in1, Vector4 in2) {
  // AUG_plantfcn

  //    This function was generated by the Symbolic Math Toolbox version 24.2.
  //    11-Aug-2025 16:49:07

  float b1 = in1[12];
  float b2 = in1[13];
  float b3 = in1[14];
  float b4 = in1[15];
  float b5 = in1[16];
  float b6 = in1[17];
  float omega1 = in1[9];
  float omega2 = in1[10];
  float omega3 = in1[11];
  float phi = in2[1];
  float q1 = in1[6];
  float q2 = in1[7];
  float q3 = in1[8];
  float tau = in2[3];
  float theta = in2[0];
  float thrust = in2[2];
  float v1 = in1[3];
  float v2 = in1[4];
  float v3 = in1[5];
  float t2 = cos(phi);
  float t3 = cos(theta);
  float t4 = sin(phi);
  float t5 = sin(theta);
  float t6 = pow(q1, 2);
  float t7 = pow(q2, 2);
  float t8 = pow(q3, 2);
  float t9 = q1 * q2 * 2.0;
  float t10 = q1 * q3 * 2.0;
  float t11 = q2 * q3 * 2.0;
  float t12 = -omega1;
  float t13 = -omega2;
  float t14 = -omega3;
  float t24 = b4 * (5.3e+1 / 1.0e+3);
  float t25 = omega1 * (5.3e+1 / 1.0e+3);
  float t15 = t6 * 2.0;
  float t16 = t7 * 2.0;
  float t17 = t8 * 2.0;
  float t18 = -t6;
  float t19 = -t7;
  float t20 = -t8;
  float t21 = b4 + t12;
  float t22 = b5 + t13;
  float t23 = b6 + t14;
  float t26 = -t25;
  float t27 = t18 + t19 + t20 + 1.0;
  float t28 = t24 + t26;
  float t29 = sqrt(t27);
  float t30 = q1 * t29 * 2.0;
  float t31 = q2 * t29 * 2.0;
  float t32 = q3 * t29 * 2.0;
  Vector18 rval;
  rval << -b1 + v1,
      -b2 + v2,
      -b3 + v3,
      t5 * thrust * (t10 + t31) * (-2.0e+2 / 1.99e+2) - t2 * t3 * thrust * (t16 + t17 - 1.0) * (2.0e+2 / 1.99e+2) + t3 * t4 * thrust * (t9 - t32) * (2.0e+2 / 1.99e+2) - 9.81e+2 / 1.0e+2,
      t5 * thrust * (t11 - t30) * (-2.0e+2 / 1.99e+2) - t3 * t4 * thrust * (t15 + t17 - 1.0) * (2.0e+2 / 1.99e+2) + t2 * t3 * thrust * (t9 + t32) * (2.0e+2 / 1.99e+2),
      t5 * thrust * (t15 + t16 - 1.0) * (2.0e+2 / 1.99e+2) + t3 * t4 * thrust * (t11 + t30) * (2.0e+2 / 1.99e+2) + t2 * t3 * thrust * (t10 - t31) * (2.0e+2 / 1.99e+2),
      q2 * t21 * (-1.0 / 2.0) + q2 * t23 - q3 * t22 * (3.0 / 2.0) + (t23 * t29) / 2.0,
      (q1 * t21) / 2.0 - q1 * t23 + q3 * t21 - (q3 * t23) / 2.0 - (t22 * t29) / 2.0,
      q1 * t22 * (3.0 / 2.0) - q2 * t21 + (q2 * t23) / 2.0 + (t21 * t29) / 2.0,
      tau * 2.0e+1 - t23 * (b5 * (5.3e+1 / 1.0e+3) - omega2 * (5.3e+1 / 1.0e+3)) * 2.0e+1 + t22 * (b6 * (5.3e+1 / 1.0e+3) - omega3 * (5.3e+1 / 1.0e+3)) * 2.0e+1,
      t23 * t28 * (1.0e+3 / 5.3e+1) + t5 * thrust * (6.0e+2 / 5.3e+1) - t21 * (b6 / 2.0e+1 - omega3 / 2.0e+1) * (1.0e+3 / 5.3e+1),
      t22 * t28 * (-1.0e+3 / 5.3e+1) + t21 * (b5 / 2.0e+1 - omega2 / 2.0e+1) * (1.0e+3 / 5.3e+1) + t3 * t4 * thrust * (6.0e+2 / 5.3e+1),
      0.0,
      0.0,
      0.0,
      0.0,
      0.0,
      0.0;
  return rval;
}
