function xAUG_dot = AUG_plantfcn(in1,in2)
%AUG_plantfcn
%    xAUG_dot = AUG_plantfcn(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    01-Sep-2025 19:21:04

a1 = in2(5,:);
a2 = in2(6,:);
a3 = in2(7,:);
b4 = in1(13,:);
b5 = in1(14,:);
b6 = in1(15,:);
omega1 = in1(10,:);
omega2 = in1(11,:);
omega3 = in1(12,:);
phi = in2(2,:);
q1 = in1(7,:);
q2 = in1(8,:);
q3 = in1(9,:);
tau = in2(4,:);
theta = in2(1,:);
thrust = in2(3,:);
v1 = in1(4,:);
v2 = in1(5,:);
v3 = in1(6,:);
t2 = q1.^2;
t3 = q2.^2;
t4 = q3.^2;
t5 = -omega1;
t6 = -omega2;
t7 = -omega3;
t14 = b4.*(5.3e+1./1.0e+3);
t15 = omega1.*(5.3e+1./1.0e+3);
t8 = -t2;
t9 = -t3;
t10 = -t4;
t11 = b4+t5;
t12 = b5+t6;
t13 = b6+t7;
t16 = -t15;
t17 = t8+t9+t10+1.0;
t18 = t14+t16;
t19 = sqrt(abs(t17));
mt1 = [v1;v2;v3;a1;a2;a3;q2.*t11.*(-1.0./2.0)+q2.*t13-q3.*t12.*(3.0./2.0)+(t13.*t19)./2.0;(q1.*t11)./2.0-q1.*t13+q3.*t11-(q3.*t13)./2.0-(t12.*t19)./2.0;q1.*t12.*(3.0./2.0)-q2.*t11+(q2.*t13)./2.0+(t11.*t19)./2.0;tau.*2.0e+1-t13.*(b5.*(5.3e+1./1.0e+3)-omega2.*(5.3e+1./1.0e+3)).*2.0e+1+t12.*(b6.*(5.3e+1./1.0e+3)-omega3.*(5.3e+1./1.0e+3)).*2.0e+1;t13.*t18.*(1.0e+3./5.3e+1)+thrust.*sin(theta).*(6.0e+2./5.3e+1)-t11.*(b6./2.0e+1-omega3./2.0e+1).*(1.0e+3./5.3e+1)];
mt2 = [t12.*t18.*(-1.0e+3./5.3e+1)+t11.*(b5./2.0e+1-omega2./2.0e+1).*(1.0e+3./5.3e+1)+thrust.*cos(theta).*sin(phi).*(6.0e+2./5.3e+1);0.0;0.0;0.0];
xAUG_dot = [mt1;mt2];
end
