function x_dot = plantfcn(in1,in2)
%PLANTFCN
%    X_DOT = PLANTFCN(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    05-Sep-2025 13:44:41

omega1 = in1(10,:);
omega2 = in1(11,:);
omega3 = in1(12,:);
phi = in2(2,:);
q1 = in1(7,:);
q2 = in1(8,:);
q3 = in1(9,:);
tau = in2(4,:);
theta = in2(1,:);
thrust = in2(3,:);
v1 = in1(4,:);
v2 = in1(5,:);
v3 = in1(6,:);
t2 = cos(phi);
t3 = cos(theta);
t4 = sin(phi);
t5 = sin(theta);
t6 = q1.^2;
t7 = q2.^2;
t8 = q3.^2;
t9 = q1.*q2.*2.0;
t10 = q1.*q3.*2.0;
t11 = q2.*q3.*2.0;
t12 = t6.*2.0;
t13 = t7.*2.0;
t14 = t8.*2.0;
t15 = -t6;
t16 = -t7;
t17 = -t8;
t18 = t15+t16+t17+1.0;
t19 = sqrt(t18);
t20 = q1.*t19.*2.0;
t21 = q2.*t19.*2.0;
t22 = q3.*t19.*2.0;
mt1 = [v1;v2;v3;t5.*thrust.*(t10+t21).*(-2.0e+2./1.99e+2)-t2.*t3.*thrust.*(t13+t14-1.0).*(2.0e+2./1.99e+2)+t3.*t4.*thrust.*(t9-t22).*(2.0e+2./1.99e+2)-9.81e+2./1.0e+2;t5.*thrust.*(t11-t20).*(-2.0e+2./1.99e+2)-t3.*t4.*thrust.*(t12+t14-1.0).*(2.0e+2./1.99e+2)+t2.*t3.*thrust.*(t9+t22).*(2.0e+2./1.99e+2);t5.*thrust.*(t12+t13-1.0).*(2.0e+2./1.99e+2)+t3.*t4.*thrust.*(t11+t20).*(2.0e+2./1.99e+2)+t2.*t3.*thrust.*(t10-t21).*(2.0e+2./1.99e+2);(omega1.*q2)./2.0+omega2.*q3.*(3.0./2.0)-omega3.*q2-(omega3.*t19)./2.0];
mt2 = [omega1.*q1.*(-1.0./2.0)-omega1.*q3+omega3.*q1+(omega3.*q3)./2.0+(omega2.*t19)./2.0;omega1.*q2-omega2.*q1.*(3.0./2.0)-(omega3.*q2)./2.0-(omega1.*t19)./2.0;tau.*2.0e+1;omega1.*omega3.*(3.0./5.3e+1)+t5.*thrust.*(6.0e+2./5.3e+1);omega1.*omega2.*(-3.0./5.3e+1)+t3.*t4.*thrust.*(6.0e+2./5.3e+1)];
x_dot = [mt1;mt2];
end
