function out1 = JacobianU(in1,in2)
%JacobianU
%    OUT1 = JacobianU(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    13-Nov-2025 17:40:26

phi = in2(2,:);
q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
tau = in2(4,:);
theta = in2(1,:);
thrust = in2(3,:);
t2 = cos(phi);
t3 = cos(theta);
t4 = sin(phi);
t5 = sin(theta);
t6 = q1.^2;
t7 = q2.^2;
t8 = q3.^2;
t9 = q1.*q2.*2.0;
t10 = q1.*q3.*2.0;
t11 = q2.*q3.*2.0;
t12 = t6.*2.0;
t13 = t7.*2.0;
t14 = t8.*2.0;
t18 = -t6;
t19 = -t7;
t20 = -t8;
t21 = t12+t13-1.0;
t22 = t12+t14-1.0;
t23 = t13+t14-1.0;
t24 = t18+t19+t20+1.0;
t25 = sqrt(t24);
t26 = q1.*t25.*2.0;
t27 = q2.*t25.*2.0;
t28 = q3.*t25.*2.0;
t29 = t11+t26;
t30 = t10+t27;
t31 = t9+t28;
mt1 = [0.0,0.0,0.0,0.0,0.0,0.0,-t3.*thrust.*(t9-t28)+t4.*t5.*t23.*thrust-t2.*t5.*t30.*thrust,t3.*t22.*thrust-t4.*t5.*t31.*thrust-t2.*t5.*thrust.*(t11-t26),-t3.*t29.*thrust+t2.*t5.*t21.*thrust-t4.*t5.*thrust.*(t10-t27),t3.*thrust.*(1.2e+1./5.0)-t4.*t5.*tau.*2.0e+1,t3.*tau.*(-1.0e+3./5.3e+1)-t4.*t5.*thrust.*(1.2e+2./5.3e+1),t2.*t5.*tau.*(-1.0e+3./5.3e+1),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-t2.*t3.*t23.*thrust-t3.*t4.*t30.*thrust,t2.*t3.*t31.*thrust-t3.*t4.*thrust.*(t11-t26),t3.*t4.*t21.*thrust+t2.*t3.*thrust.*(t10-t27),t2.*t3.*tau.*2.0e+1];
mt2 = [t2.*t3.*thrust.*(1.2e+2./5.3e+1),t3.*t4.*tau.*(-1.0e+3./5.3e+1),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-t5.*(t9-t28)-t3.*t4.*t23+t2.*t3.*t30,t5.*t22+t3.*t4.*t31+t2.*t3.*(t11-t26),-t5.*t29-t2.*t3.*t21+t3.*t4.*(t10-t27),t5.*(1.2e+1./5.0),t3.*t4.*(1.2e+2./5.3e+1),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t3.*t4.*2.0e+1,t5.*(-1.0e+3./5.3e+1),t2.*t3.*(1.0e+3./5.3e+1),0.0,0.0,0.0];
out1 = reshape([mt1,mt2],15,4);
end
