function x_dot = nominalDynamics(in1,in2)
%nominalDynamics
%    X_DOT = nominalDynamics(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    16-Oct-2025 12:09:11

b4 = in1(13,:);
b5 = in1(14,:);
b6 = in1(15,:);
omega1 = in1(10,:);
omega2 = in1(11,:);
omega3 = in1(12,:);
phi = in2(2,:);
q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
tau = in2(4,:);
theta = in2(1,:);
thrust = in2(3,:);
v1 = in1(7,:);
v2 = in1(8,:);
v3 = in1(9,:);
t2 = cos(phi);
t3 = cos(theta);
t4 = sin(phi);
t5 = sin(theta);
t6 = q1.^2;
t7 = q2.^2;
t8 = q3.^2;
t9 = q1.*q2.*2.0;
t10 = q1.*q3.*2.0;
t11 = q2.*q3.*2.0;
t12 = -omega1;
t13 = -omega2;
t14 = -omega3;
t24 = b4.*(5.3e+1./1.0e+3);
t25 = omega1.*(5.3e+1./1.0e+3);
t15 = t6.*2.0;
t16 = t7.*2.0;
t17 = t8.*2.0;
t18 = -t6;
t19 = -t7;
t20 = -t8;
t21 = b4+t12;
t22 = b5+t13;
t23 = b6+t14;
t26 = -t25;
t27 = t18+t19+t20+1.0;
t28 = t24+t26;
t29 = sqrt(t27);
t30 = q1.*t29.*2.0;
t31 = q2.*t29.*2.0;
t32 = q3.*t29.*2.0;
mt1 = [q2.*t23.*(-1.0./2.0)+(q3.*t22)./2.0-(t21.*t29)./2.0;(q1.*t23)./2.0-(q3.*t21)./2.0-(t22.*t29)./2.0;q1.*t22.*(-1.0./2.0)+(q2.*t21)./2.0-(t23.*t29)./2.0;v1;v2;v3;t5.*thrust.*(t9-t32).*(-2.0e+2./1.99e+2)-t3.*t4.*thrust.*(t16+t17-1.0).*(2.0e+2./1.99e+2)+t2.*t3.*thrust.*(t10+t31).*(2.0e+2./1.99e+2);t5.*thrust.*(t15+t17-1.0).*(2.0e+2./1.99e+2)+t3.*t4.*thrust.*(t9+t32).*(2.0e+2./1.99e+2)+t2.*t3.*thrust.*(t11-t30).*(2.0e+2./1.99e+2)];
mt2 = [t5.*thrust.*(t11+t30).*(-2.0e+2./1.99e+2)-t2.*t3.*thrust.*(t15+t16-1.0).*(2.0e+2./1.99e+2)+t3.*t4.*thrust.*(t10-t31).*(2.0e+2./1.99e+2)-9.81e+2./1.0e+2;t5.*thrust.*1.2e+1-t23.*(b5.*(5.3e+1./1.0e+3)-omega2.*(5.3e+1./1.0e+3)).*2.0e+1+t22.*(b6.*(5.3e+1./1.0e+3)-omega3.*(5.3e+1./1.0e+3)).*2.0e+1;t23.*t28.*(1.0e+3./5.3e+1)-t21.*(b6./2.0e+1-omega3./2.0e+1).*(1.0e+3./5.3e+1)+t3.*t4.*thrust.*(6.0e+2./5.3e+1)];
mt3 = [tau.*(1.0e+3./5.3e+1)-t22.*t28.*(1.0e+3./5.3e+1)+t21.*(b5./2.0e+1-omega2./2.0e+1).*(1.0e+3./5.3e+1);0.0;0.0;0.0];
x_dot = [mt1;mt2;mt3];
end
